version: '3.7'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 091712Ch@17
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mydb_data:/var/lib/mysql
volumes:
  mydb_data:
